---
- name: run apt-get update
  become: true
  apt:
    update_cache: yes

- name: run apt-get upgrade
  become: true
  apt:
    upgrade: dist

- name: update sshd_config
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?Port 22'
    line: 'Port 6522'
    backup: yes
  notify:
    - restart sshd

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: copy config file to /etc/logrotate.d
  become: true
  copy:
    src: "nginx.conf"
    dest: "/etc/logrotate.d/nginx.conf"
    owner: root
    group: root
    mode: 0644

- name: install packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    u_cache: yes
  with_items:
    - wget
    - unzip
    - curl
    - git
    - jq
    - apache2
    - mysql-client
    - php

- name: create tmp folder
  file:
    path: /tmp/fefiles
    state: directory

- name: download zip from S3
  amazon.aws.aws_s3:
    bucket: skillup-s3-aa.achico-001
    mode: get
    object: frontend.zip
    dest: "/tmp/fefiles/frontend.zip"

- name: extract zip file to /var/www/html/
  become: true
  unarchive:
    src: "/tmp/fefiles/frontend.zip"
    dest: "/var/www/html"

- name: set private ip address in index.html
  become: true
  replace:
    path: /var/www/html/index.html
    regexp: 'pri_ip_address(.*)'
    replace: "{{ pri_ip_address }}"
  notify: 
    - restart apache2

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: delete tmp folder
  file:
    path: /tmp/fefiles
    state: absent

- name: create group
  become: true
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - apple
    - banana
    - carrot

- name: create users
  become: true
  user:
    name: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - apple
    - banana
    - carrot

- name: delete user carrot
  become: true
  user:
    name: carrot
    state: absent
    remove: yes

- name: set permission to 0600
  become: true
  file:
    path: /var/log/syslog
    mode: '0600'